@.NETHostAddress = http://localhost:5140
@DockerHostAddress =  http://localhost:5000

### Get All Houses (Docker)
GET @DockerHostAddress/api/house?minPrice=150000&maxPrice=300000
Accept: application/json

### Get All Houses (.NET)
GET @.NETHostAddress/api/house?minPrice=150000&maxPrice=300000
Accept: application/json

### Update Customer Financial Information (Docker)
PUT @DockerHostAddress/api/customer/1/financial-info
Content-Type: application/json
Accept: application/json

{
    "income": 85000.50,
    "creditScore": 750
}

### Update Customer Financial Information (.NET)
PUT @.NETHostAddress/api/customer/1/financial-info
Content-Type: application/json
Accept: application/json

{
    "income": 85000.50,
    "creditScore": 750
}

