version: '3.8'

services:
  buy-my-house-api:
    build:
      context: ./buy-my-house.api  
      dockerfile: Dockerfile       
    ports:
      - "5000:5000"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    networks:
      - buy-my-house-network

  buy-my-house-functions:
    build:
      context: ./buy-my-house.functions  
      dockerfile: Dockerfile             
    ports:
      - "5002:5002"  
    environment:
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - ASPNETCORE_URLS=http://0.0.0.0:5002
    networks:
      - buy-my-house-network

networks:
  buy-my-house-network:
    driver: bridge
