version: '3.8'

services:
  buy-my-house-api:
    build:
      context: ./buy-my-house.api  
      dockerfile: Dockerfile       
    ports:
      - "5000:5000"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    networks:
      - buy-my-house-network

  buy-my-house-functions:
    build:
      context: ./buy-my-house.functions  
      dockerfile: Dockerfile             
    ports:
      - "5002:5002"  
    environment:
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - ASPNETCORE_URLS=http://0.0.0.0:5002
    networks:
      - buy-my-house-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123 
    ports:
      - "1433:1433"
    networks:
      - buy-my-house-network
    volumes:
      - sqlserverdata:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002 --location /workspace --debug /workspace/debug.log"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - buy-my-house-network
    volumes:
      - ./azurite:/workspace

  smtp-server:
    image: namshi/smtp
    container_name: smtp-server
    ports:
      - "1025:25"
    networks:
      - buy-my-house-network
    environment:
      - RELAY_NETWORKS=127.0.0.0/8
      - ALLOWED_SENDER_DOMAINS=*
    restart: always

networks:
  buy-my-house-network:
    driver: bridge

volumes:
  sqlserverdata:
  azuritedata:
